---
- name: Download Malware Samples from MalwareBazaar
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # --- Configuration ---
    # You can get a key by registering at https://bazaar.abuse.ch/account/
    malwarebazaar_api_key: "YOUR_API_KEY_HERE"
    malwarebazaar_api_url: "https://mb-api.abuse.ch/api/v1/"
    download_dir: "./malware_samples_ansible"
    hours_to_check: 24

  tasks:
    - name: Ensure p7zip-full (for 7z) is installed for AES support
      become: yes
      ansible.builtin.package:
        name: p7zip-full
        state: present

    - name: Create download directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory
        mode: '0755'

    - name: Get list of recent malware samples
      ansible.builtin.uri:
        url: "{{ malwarebazaar_api_url }}"
        method: POST
        body_format: form-urlencoded
        body:
          query: "recent_detections"
          hours: "{{ hours_to_check }}"
        headers:
          Auth-Key: "{{ malwarebazaar_api_key }}"
      register: malware_list_response

    - name: Fail if API query was not successful
      ansible.builtin.fail:
        msg: "Failed to get malware list. API status: {{ malware_list_response.json.query_status }}"
      when: malware_list_response.json.query_status != 'ok'

    - name: Download and extract each sample
      ansible.builtin.include_tasks: process_sample.yaml
      loop: "{{ malware_list_response.json.data }}"
      loop_control:
        loop_var: sample
        label: "{{ sample.file_name | default(sample.sha256_hash) }}"

    - name: Display success message
      ansible.builtin.debug:
        msg: "Malware sample download process completed. Files are in {{ download_dir }}"